frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/muhammadfarhanz/twitter-frontend
    tag: 19df47b77256869fc022cc6010bf62666d7eae3c
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
backend:
  replicaCount: 2
  image:
    repository: ghcr.io/muhammadfarhanz/twitter-backend
    tag: 4f91c4b2ddf9ae37043d4b11b91e151069f7d079
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
