apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-be-deployment
  labels:
    app: twitter-be
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  namespace: { { .Release.Namespace } }
spec:
  replicas: { { .Values.backend.replicaCount } }
  selector:
    matchLabels:
      app: twitter-be
  template:
    metadata:
      labels:
        app: twitter-be
    spec:
      containers:
        - name: {{ .Chart.Name }}-be
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-be-service
  labels:
    app: twitter-be
    chart: {{ .Chart.Name }}- {{ .Chart.Version }}
    release: {{ .Release.Name }}
  namespace: { { .Release.Namespace } }
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: twitter-be
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}