defaultRules:
  alertmanager: false
  kubeEtcd: false
alertmanager:
  enabled: false
grafana:
  enabled: true
  fullnameOverride: grafana
  adminPassword: admin
prometheusOperator:
  enabled: true
  fullnameOverride: prometheus-operator
kube-state-metrics:
  enabled: true
  fullnameOverride: kube-state-metrics
kubelet:
  serviceMonitor:
    enabled: true
    interval: 120s
prometheus:
  serviceAccount:
    create: true
    name: "prometheus-k8s"
  prometheusSpec:
    retention: 2d
    tsdb:
      walCompression: true
prometheus-node-exporter:
  enabled: true
  fullnameOverride: node-exporter
  prometheus:
    serviceMonitor:
      enabled: true
      interval: 120s
kubeEtcd:
  enabled: false
