apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.20.0
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/charts/infra/cert-manager/values-prod.yaml
    - repoURL: https://github.com/MuhammadFarhanz/argocd-kubernetes-gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
