apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.6.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/charts/infra/external-secret/values-prod.yaml
    - repoURL: https://Muhammadfarhanz.github.io/argocd-kubernetes-gitops
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
