# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus-stack
#   namespace: argocd
# spec:
#   destination:
#     namespace: monitoring
#     server: https://kubernetes.default.svc
#   project: default
#   sources:
#     - repoURL: https://prometheus-community.github.io/helm-charts # Official Helm Chart
#       chart: kube-prometheus-stack
#       targetRevision: 86.2.3
#       helm:
#         valueFiles:
#           - $values/charts/infra/kube-prometheus/values-prod.yaml # Relative path from repo root
#     - repoURL: https://github.com/MuhammadFarhanz/argocd-kubernetes-gitops.git
#       targetRevision: main
#       ref: values # Reference for $values
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - ServerSideApply=true
#       - CreateNamespace=true
