apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-be-deployment
  labels:
    app: twitter-be
  namespace: twitter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twitter-be
  template:
    metadata:
      labels:
        app: twitter-be
    spec:
      containers:
        - name: backend
          image: ghcr.io/Muhammad-farhanz/twitter-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-be-service
  labels:
    app: twitter-be
  namespace: twitter
spec:
  type: ClusterIP
  selector:
    app: twitter-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
