apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-fe-deployment
  labels:
    app: twitter-fe
  namespace: twitter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twitter-fe
  template:
    metadata:
      labels:
        app: twitter-fe
    spec:
      containers:
        - name: frontend
          image: ghcr.io/Muhammad-farhanz/twitter-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-fe-service
  labels:
    app: twitter-fe
  namespace: twitter
spec:
  type: ClusterIP
  selector:
    app: twitter-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
