frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/muhammadfarhanz/twitter-frontend
    tag: 19df47b77256869fc022cc6010bf62666d7eae3c
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
backend:
  replicaCount: 2
  image:
    repository: ghcr.io/muhammadfarhanz/twitter-backend
    tag: 8f93cbbe0131a646aad3f807b9d54d3a656a5a50
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
