apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-be-deployment
  labels:
    app: twitter-be
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: twitter-be
  template:
    metadata:
      labels:
        app: twitter-be
    spec:
      containers:
        - name: {{ .Chart.Name }}-be
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}

