apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twitter-app-secrets
  namespace: twitter
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: infisical
    kind: SecretStore 
  target:
    name: twitter-secret 
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
